"""Licence-plate RECOGNIZER: model classes, preprocessing and decoding (Phase 2 models, used by Phase 3).

This file is the exact code the trained weights were produced with (it was generated by the Kaggle training
notebook as `lpr_models.py` and ships inside the model bundle). Depends only on torch, torchvision, numpy, PIL.

    x = preprocess(crop_rgb)                       # [3, 64, 256] float tensor
    digit_logits, letter_logits = model(x[None])   # [1, 7, 10], [1, n_letters]
    text = decode((digit_logits, letter_logits), letter_vocab)
"""
import json
import os

import numpy as np
import torch
import torch.nn as nn
from PIL import Image
from torchvision import models

INPUT_SIZE = (64, 256)  # (H, W): crops are letterboxed (aspect kept), never stretched
PAD_VALUE = 114  # gray padding for letterbox and augmentation fill
MEAN = (0.485, 0.456, 0.406)  # ImageNet statistics, used by both models
STD = (0.229, 0.224, 0.225)
DIGIT_VOCAB = list("0123456789")
PLATE_LEN = 8
LETTER_POS = 2  # label layout: D D L D D D D D  (2 digits, letter, 3 digits, 2-digit region)
DIGIT_POS = (0, 1, 3, 4, 5, 6, 7)

_DIGIT_TRANS = str.maketrans("۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩", "01234567890123456789")


def normalize_label(text):
    """Canonical plate string: ASCII digits, no ZWJ/ZWNJ/spaces, Persian (not Arabic) yeh/kaf."""
    t = str(text).strip().translate(_DIGIT_TRANS)
    for ch in ("‍", "‌", " ", "‏", "‎"):
        t = t.replace(ch, "")
    return t.replace("ي", "ی").replace("ك", "ک")


def to_pil(img, bgr=False):
    """PIL image or HxWxC uint8 numpy array (RGB, or BGR from cv2 with bgr=True) -> RGB PIL image."""
    if isinstance(img, Image.Image):
        return img.convert("RGB")
    a = np.asarray(img)
    if a.ndim == 2:
        a = np.stack([a] * 3, axis=-1)
    elif bgr:
        a = a[..., ::-1]
    return Image.fromarray(np.ascontiguousarray(a[..., :3]).astype(np.uint8)).convert("RGB")


def letterbox(img, size=INPUT_SIZE, pad_value=PAD_VALUE):
    """Resize keeping the aspect ratio so the image fits in size=(H, W), then pad (centred) with gray."""
    H, W = size
    w, h = img.size
    s = min(W / w, H / h)
    nw, nh = max(1, round(w * s)), max(1, round(h * s))
    canvas = Image.new("RGB", (W, H), (pad_value,) * 3)
    canvas.paste(img.resize((nw, nh), Image.BILINEAR), ((W - nw) // 2, (H - nh) // 2))
    return canvas


def to_tensor(img):
    """Letterboxed RGB PIL image -> normalized float tensor [3, H, W]."""
    t = torch.from_numpy(np.asarray(img, dtype=np.float32) / 255.0).permute(2, 0, 1)
    return (t - torch.tensor(MEAN).view(3, 1, 1)) / torch.tensor(STD).view(3, 1, 1)


def preprocess(img, bgr=False):
    """Eval-time preprocessing (identical to training without augmentation): letterbox + normalize."""
    return to_tensor(letterbox(to_pil(img, bgr=bgr)))


def crop_with_padding(img, xyxy, pad=0.05):
    """Crop box (x1, y1, x2, y2 in pixels) enlarged by `pad` x box size on each side, clamped to the image.
    Works for numpy arrays (H, W, C) and PIL images; returns the same type."""
    x1, y1, x2, y2 = [float(v) for v in xyxy]
    bw, bh = x2 - x1, y2 - y1
    W, H = img.size if isinstance(img, Image.Image) else (img.shape[1], img.shape[0])
    x1, y1 = max(0, int(round(x1 - pad * bw))), max(0, int(round(y1 - pad * bh)))
    x2, y2 = min(W, int(round(x2 + pad * bw))), min(H, int(round(y2 + pad * bh)))
    return img.crop((x1, y1, x2, y2)) if isinstance(img, Image.Image) else img[y1:y2, x1:x2]


def load_config(path=None):
    path = path or os.path.join(os.path.dirname(os.path.abspath(__file__)), "lpr_config.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def decode_batch(logits, letter_vocab=None):
    """(digit_logits [B,7,10], letter_logits [B,L]) -> list of plate strings like '12ب34567'."""
    digit_logits, letter_logits = logits
    if digit_logits.dim() == 2:
        digit_logits, letter_logits = digit_logits[None], letter_logits[None]
    if letter_vocab is None:
        letter_vocab = load_config()["letter_vocab"]
    out = []
    for d, l in zip(digit_logits.argmax(-1).tolist(), letter_logits.argmax(-1).tolist()):
        ds = "".join(DIGIT_VOCAB[i] for i in d)
        out.append(ds[:2] + letter_vocab[l] + ds[2:])
    return out


def decode(logits, letter_vocab=None):
    """Logits of ONE plate (batch of 1 or unbatched) -> plate string. Use decode_batch for batches."""
    texts = decode_batch(logits, letter_vocab)
    if len(texts) != 1:
        raise ValueError(f"decode() expects one plate, got {len(texts)}; use decode_batch()")
    return texts[0]



class LPRHead(nn.Module):
    """Multi-head output shared by both models: 7 independent digit classifiers + 1 letter classifier."""

    def __init__(self, in_ch, n_letters, mid_ch=256, pool_w=8, hidden=512, dropout=0.3):
        super().__init__()
        self.n_digit_slots = len(DIGIT_POS)
        self.reduce = nn.Sequential(nn.Conv2d(in_ch, mid_ch, 1, bias=False), nn.BatchNorm2d(mid_ch), nn.ReLU(inplace=True))
        self.pool = nn.AdaptiveAvgPool2d((1, pool_w))  # pool height, keep pool_w columns (left -> right)
        self.fc = nn.Linear(mid_ch * pool_w, hidden)
        self.norm = nn.LayerNorm(hidden)
        self.act = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(dropout)
        self.digit_head = nn.Linear(hidden, self.n_digit_slots * len(DIGIT_VOCAB))  # = 7 separate 10-way heads
        self.letter_head = nn.Linear(hidden, n_letters)
        nn.init.kaiming_normal_(self.reduce[0].weight, mode="fan_out", nonlinearity="relu")
        nn.init.kaiming_normal_(self.fc.weight, nonlinearity="relu")
        nn.init.zeros_(self.fc.bias)
        for head in (self.digit_head, self.letter_head):
            nn.init.normal_(head.weight, std=0.01)
            nn.init.zeros_(head.bias)

    def forward(self, f):
        x = self.drop(self.pool(self.reduce(f)).flatten(1))
        x = self.drop(self.act(self.norm(self.fc(x))))
        return self.digit_head(x).view(-1, self.n_digit_slots, len(DIGIT_VOCAB)), self.letter_head(x)


class ResidualBlock(nn.Module):
    def __init__(self, in_ch, out_ch, stride=1, drop=0.0):
        super().__init__()
        self.conv1 = nn.Conv2d(in_ch, out_ch, 3, stride, 1, bias=False)
        self.bn1 = nn.BatchNorm2d(out_ch)
        self.relu1 = nn.ReLU(inplace=True)
        self.drop = nn.Dropout2d(drop) if drop > 0 else nn.Identity()
        self.conv2 = nn.Conv2d(out_ch, out_ch, 3, 1, 1, bias=False)
        self.bn2 = nn.BatchNorm2d(out_ch)
        self.relu2 = nn.ReLU(inplace=True)
        self.shortcut = nn.Identity()
        if stride != 1 or in_ch != out_ch:
            self.shortcut = nn.Sequential(nn.Conv2d(in_ch, out_ch, 1, stride, bias=False), nn.BatchNorm2d(out_ch))

    def forward(self, x):
        y = self.bn2(self.conv2(self.drop(self.relu1(self.bn1(self.conv1(x))))))
        return self.relu2(y + self.shortcut(x))


class ScratchLPRNet(nn.Module):
    """Model I: residual CNN trained from scratch. Input [B,3,64,256] -> ([B,7,10], [B,n_letters])."""

    def __init__(self, n_letters, widths=(64, 128, 256, 256), dropout=0.3):
        super().__init__()
        self.stem = nn.Sequential(nn.Conv2d(3, 32, 3, 1, 1, bias=False), nn.BatchNorm2d(32), nn.ReLU(inplace=True))
        strides = (2, 2, 2, (2, 1))  # 64x256 -> 32x128 -> 16x64 -> 8x32 -> 4x32
        drops = (0.0, 0.0, 0.05, 0.1)
        stages, c = [], 32
        for w, s, d in zip(widths, strides, drops):
            stages.append(nn.Sequential(ResidualBlock(c, w, s, d), ResidualBlock(w, w, 1, d)))
            c = w
        self.stages = nn.Sequential(*stages)
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)
        for m in self.modules():
            if isinstance(m, ResidualBlock):
                nn.init.zeros_(m.bn2.weight)  # each residual branch starts as identity
        self.head = LPRHead(c, n_letters, mid_ch=256, pool_w=16, dropout=dropout)

    def forward(self, x):
        return self.head(self.stages(self.stem(x)))



class PretrainedLPRNet(nn.Module):
    """Model II: ImageNet-pretrained torchvision backbone + the shared LPRHead."""

    def __init__(self, n_letters, pretrained=True, backbone="mobilenet_v3_large", dropout=0.3):
        super().__init__()
        if backbone == "mobilenet_v3_large":
            net = models.mobilenet_v3_large(weights=models.MobileNet_V3_Large_Weights.IMAGENET1K_V2 if pretrained else None)
            out_ch = 960
        elif backbone == "efficientnet_b0":
            net = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.IMAGENET1K_V1 if pretrained else None)
            out_ch = 1280
        else:
            raise ValueError(backbone)
        self.backbone_name = backbone
        self.features = net.features  # stride 32: [B,3,64,256] -> [B,out_ch,2,8]
        self.head = LPRHead(out_ch, n_letters, mid_ch=256, pool_w=8, dropout=dropout)
        self.backbone_frozen = False

    def set_backbone_trainable(self, trainable):
        self.backbone_frozen = not trainable
        for p in self.features.parameters():
            p.requires_grad = trainable
        self.train(self.training)

    def train(self, mode=True):
        super().train(mode)
        if self.backbone_frozen:
            self.features.eval()  # frozen stage: keep ImageNet BatchNorm statistics
        return self

    def forward(self, x):
        return self.head(self.features(x))


def build_model(arch, n_letters, pretrained=False, backbone="mobilenet_v3_large"):
    """arch: 'scratch' | 'pretrained'. Use pretrained=False when loading a trained state_dict (no download)."""
    if arch == "scratch":
        return ScratchLPRNet(n_letters)
    if arch == "pretrained":
        return PretrainedLPRNet(n_letters, pretrained=pretrained, backbone=backbone)
    raise ValueError(arch)
